os: linux
dist: focal
language: java
jdk: openjdk17
cache:
  directories:
    - "$HOME/.m2"
branches:
  only:
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
addons:
  sonarcloud:
    organization: molgenis
    token:
      secure: bozaYygDUEHxneDKmdGGb5ThB2wu5WfG+hNbAvHE6KOz1jP+VAM6r94rQhWzNSFspmTv5XRD3rcD9FZKLONzGifeWT6gjrKn/FSdYnDGLN5nRm0ARHiE/74Qr25uIsnxcZV2vV1iatxfR9CjMSXVYQc3r+IrIfgxuTt4zy7BUeVmL02cicwcX2OJFm0MA5VU4Kbi+hPknegw9IhdpHEnQZanyGqX1/bSxCqQkYNJ0tLtThhJ8/DOO+jWdEPHvHRULI9YWUCccdBH5/pJUAj67Fne8tImeHywO+sDklXgwZ2D0EWwx9oBGOVwXfaobVOewnz3+wE3+aFxyivKsQeeqMBeHjf9tYvZBUzjFXJaWQVcUU/YdrJUzhLXjhKZQ8V0eKjHBSKZ0KajKBvN0cBjAnAMR11UZf2Ro0M6uqhW03ihCKxFcmIUNCFsuW8lMDCm6l4urA09r+zW+p5/LUMtzGfAPaJL4gqP8SDJi2dzwpoaUbxCiCNgImofWMHKVzP17JqhOWxFndyVHE1k9Qhfmy1b0qE6nAVl1UVNvavRqubT5AwP7H4iNc/dfrd+lNwSE9oHZ+xEfLd/6MCjk+Q/VI5ON8Cvyjv0ZwjL9xOs8QfdY3iC/mHfVo7SL7rhC64vLOmyMxK9w465HCv1A/kUOeEIyWm2uS3hWuBi+OnHBKo=
script:
  - mvn clean install sonar:sonar -Pcoverage -Dsonar.projectKey=molgenis_vip-decision-tree
deploy:
  provider: releases
  api_key:
    secure: flAkb1fMyrE6zk0GnFXIo3RYYn9OC2QdvJXfSPzX0RoyuXMY/xvRuNJbH+KRsR03H9exo6H+Gi+iFWxWTFxjpoq3lInlYTMu4JRaxOcsgab3NEXE6qa9lBCv9F0VSVqGbNgND/ndzdZ34db3s2a4vIEc9rGH9ek0lAxVM5liEfhn+gl6k4ld7al+PWDyVYyQ8sNDUgdUQieAOuXhkaXph11alJTw74TskUQ1qg1279ONoRFfTdu19gyHOeTD8eUS9A1MLr4HlEqZas5bNtS/nonK/7/j5+cbkGlBVWiwkvc4p5sCBEBmYvuHw0hjfkTF/S9y9ZAbyDtdwRw0ZeXfoJDM16k8P/A9YUR8MPPcTmU+yqobq57bt86zW/qUfiMPfpGnUj5dKJeLQJ/uoSSVg/eQjX1z9SoN1tsjJXV4H2oStTyshcrYpbSJrGEgbuYUYbDMmIQEa+wB/G0J2JHwfOat59PVw6fjgOL4k+j82m3h3xPFcJm5PF6V1g3PRACVipCknAq/OwhjUtGutTPAiDyhk5/QmNdc+MvpN2UeDXgd3FbKygMjAknZaEH/lEF1kgEJyVJDpyIGfdhh/NeIVP4+XMDeu+MCry4PNgkPzKrJCHCA1K7e9ybo78N/n1k7yUdKveiykBgtDB88FQVYA+6EzVfEXW4kC2OFzIlJb4w=
  file: target/vcf-decision-tree.jar
  prerelease: true
  on:
    tags: true
  edge: true # opt in to dpl v2
