os: linux
dist: focal
language: java
jdk: openjdk17
cache:
  directories:
    - "$HOME/.m2"
branches:
  only:
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
addons:
  sonarcloud:
    organization: molgenis
    token:
      secure: bozaYygDUEHxneDKmdGGb5ThB2wu5WfG+hNbAvHE6KOz1jP+VAM6r94rQhWzNSFspmTv5XRD3rcD9FZKLONzGifeWT6gjrKn/FSdYnDGLN5nRm0ARHiE/74Qr25uIsnxcZV2vV1iatxfR9CjMSXVYQc3r+IrIfgxuTt4zy7BUeVmL02cicwcX2OJFm0MA5VU4Kbi+hPknegw9IhdpHEnQZanyGqX1/bSxCqQkYNJ0tLtThhJ8/DOO+jWdEPHvHRULI9YWUCccdBH5/pJUAj67Fne8tImeHywO+sDklXgwZ2D0EWwx9oBGOVwXfaobVOewnz3+wE3+aFxyivKsQeeqMBeHjf9tYvZBUzjFXJaWQVcUU/YdrJUzhLXjhKZQ8V0eKjHBSKZ0KajKBvN0cBjAnAMR11UZf2Ro0M6uqhW03ihCKxFcmIUNCFsuW8lMDCm6l4urA09r+zW+p5/LUMtzGfAPaJL4gqP8SDJi2dzwpoaUbxCiCNgImofWMHKVzP17JqhOWxFndyVHE1k9Qhfmy1b0qE6nAVl1UVNvavRqubT5AwP7H4iNc/dfrd+lNwSE9oHZ+xEfLd/6MCjk+Q/VI5ON8Cvyjv0ZwjL9xOs8QfdY3iC/mHfVo7SL7rhC64vLOmyMxK9w465HCv1A/kUOeEIyWm2uS3hWuBi+OnHBKo=
script:
  - mvn clean install sonar:sonar -Pcoverage -Dsonar.projectKey=molgenis_vip-decision-tree
deploy:
  provider: releases
  api_key:
    secure: EQdSh1+Z1iLrcCdtDNEdtiJ/klP5NdBZ42MPJywgM4nweAWmAestIPHji4Z1xdDQy7rF5zVLUMXXnFY8nPRTosG8vsh/sFT3RASNXHV0KnVAKkJML9UevcVeLsNSI96vXjx1uHtdZ1kWZFb4VeT3FaTLQlaI4X3UCTVJnlyRwIBjhBPxBs760SWWnvcF9sWDim9wwFAYp3KE57I4PqqqnVRf/GWE4f3hD4eYTd2S4xLsKxLSHor9CoAXFWJYBewdObMsm0VunicZLPIj3Mor8phqRbvOQsT2NCohDIB1rx6/bfnLs66ix7YnSuX6ZzJJNcszZtLvJPC938NmV1v+GLajwvVyxo163M1kCwPGx2N/o563M1ACsyzJ9RlqH8FUtHj3pk99oqy2pqxXo50GegWUIii3Ue6kF+sGWTqNPw4cXYAUfsercHlx07POw4iofzncYeyV7WaHGzrFyL32C/VuEd6YWYmCx+VwjGm/Qxj+uLfcH5/WtRjV/5AoeVciPmbd6ktOEJ1D1FDlaws/SEQQu6XdGxnzgNul1tHgXTKnJqb5HO4r9GUBLmAH1IpIiZCP4ZfqTB4A1/iFVuMKQDNhyBwrNfj3fIKOp7491dSNovI3l3qid39rfWPnJAbU2zq3m2uowJFToHx76zPGY1gb3xv9W1MP9nWU8NbHOtU=
  file: target/vcf-decision-tree.jar
  prerelease: true
  on:
    tags: true
  edge: true # opt in to dpl v2
